#!/bin/bash -e
# Copyright 2014-2018 XenoTech. See LICENSE for legal details.

if [ -f demos/Makefile ]; then
	pushd demos >/dev/null
	make clean && rm -f Makefile
	popd >/dev/null
fi
if [ -f Makefile ]; then
	make mrproper && rm -f Makefile
fi
dir="${PWD##*/}"
cd ..
tar jcf "$dir".tar.xz --exclude="$dir"/.git --exclude="$dir/docs/html" --exclude=CODING_STYLE --exclude="$dir/docs/DoxyFile" --exclude="$dir/docs/DoxyIcon.jpg" --exclude=tags --exclude='*.swp' --exclude='*.vim' --exclude='.gitignore' --exclude='release' --exclude='dropped' "$dir"
# Make sure environment is sane
cd "$dir"
git checkout configure
# Continue deploying
cd ..
md5sum "$dir".tar.xz >"$dir".tar.xz.md5sum
shasum "$dir".tar.xz >"$dir".tar.xz.shasum
